# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_app', '0003_auto_20161118_1344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='property_search_vw',
        ),
    ]
