# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integration_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
